<?php
  $token = str_replace("bearer ", "", $_SERVER['HTTP_ID']);
  header('Content-type: application/json; charset=utf-8');
?>

[
   {
      "channelCode":"MAPP",
      "clickThroughUrl":"gmalite://gmalite-smartweb?weburl=https://sommerchancenapp.mcd.ddbcph.dk/",
      "closestVenue":null,
      "contentTagReferenceCodes":[

      ],
      "contentUrl":"",
      "dailyEndTime":null,
      "dailyStartTime":null,
      "dateCreated":"2017-04-26T06:20:03Z",
      "dateModified":"2017-05-08T05:22:44Z",
      "daysOfWeek":[
         0,
         1,
         2,
         3,
         4,
         5,
         6
      ],
      "description":"Spil SommerChancen og vind masser af lækre præmier",
      "distanceToClosestVenue":null,
      "endDate":"2017-07-16T21:59:00Z",
      "eventStartDateTime":null,
      "extendedData":null,
      "id":96,
      "image":"asi96_high_da-2.png",
      "imageDescription":"Spil SommerChancen og vind masser af lækre præmier",
      "isActive":true,
      "isAvailableAllStores":true,
      "merchantId":564,
      "placementCode":"CD",
      "startDate":"2017-05-07T08:00:00Z",
      "title":"SommerChancen",
      "venues":null,
      "weight":500
   },
   {
      "channelCode":"MAPP",
      "clickThroughUrl":"gmalite://gmalite-smartweb?weburl=https://XXX.XX/index.php?token=<?=$token?>",
      "closestVenue":null,
      "contentTagReferenceCodes":[

      ],
      "contentUrl":"",
      "dailyEndTime":null,
      "dailyStartTime":null,
      "dateCreated":"2017-03-28T08:45:41Z",
      "dateModified":"2017-05-05T09:30:04Z",
      "daysOfWeek":[
         0,
         1,
         2,
         3,
         4,
         5,
         6
      ],
      "description":"Velkommen til den nye McDonald's app. Tryk her for mere information omkring hvordan du bruger app'en.",
      "distanceToClosestVenue":null,
      "endDate":"2018-04-03T21:59:00Z",
      "eventStartDateTime":null,
      "extendedData":null,
      "id":78,
      "image":"asi78_high_da-2.png",
      "imageDescription":"Velkommen til den nye McDonald's app. Tryk her for mere information omkring hvordan du bruger app'en.",
      "isActive":true,
      "isAvailableAllStores":true,
      "merchantId":564,
      "placementCode":"CD",
      "startDate":"2017-04-02T22:00:00Z",
      "title":"Velkommen!",
      "venues":null,
      "weight":99
   },
   {
      "channelCode":"MAPP",
      "clickThroughUrl":"gmalite://gmalite-offers",
      "closestVenue":null,
      "contentTagReferenceCodes":[

      ],
      "contentUrl":"",
      "dailyEndTime":null,
      "dailyStartTime":null,
      "dateCreated":"2017-03-27T11:56:52Z",
      "dateModified":"2017-04-06T04:39:52Z",
      "daysOfWeek":[
         0,
         1,
         2,
         3,
         4,
         5,
         6
      ],
      "description":"Under 'Kuponer' får du altid et godt tilbud på alt fra menuer til tilbehør. Tryk her for at se dine kuponer.",
      "distanceToClosestVenue":null,
      "endDate":"2018-04-03T21:59:00Z",
      "eventStartDateTime":null,
      "extendedData":null,
      "id":74,
      "image":"asi74_high_en-2.png",
      "imageDescription":"Mine kuponer\r\n\r\nUnder 'Kuponer' får du altid et godt tilbud på alt fra menuer til tilbehør. Tryk her for at se dine kuponer.",
      "isActive":true,
      "isAvailableAllStores":true,
      "merchantId":564,
      "placementCode":"CD",
      "startDate":"2017-04-02T22:00:00Z",
      "title":"Mine kuponer",
      "venues":null,
      "weight":90
   },
   {
      "channelCode":"MAPP",
      "clickThroughUrl":"gmalite://gmalite-smartweb?weburl=https://gmaliteapp.mcd.ddbcph.dk/campaign/homestyle/",
      "closestVenue":null,
      "contentTagReferenceCodes":[

      ],
      "contentUrl":"",
      "dailyEndTime":null,
      "dailyStartTime":null,
      "dateCreated":"2017-04-03T10:48:31Z",
      "dateModified":"2017-04-06T04:41:21Z",
      "daysOfWeek":[
         0,
         1,
         2,
         3,
         4,
         5,
         6
      ],
      "description":"Vælg mellem Legacy, Chicken Bacon og Tasty. Se mere her.",
      "distanceToClosestVenue":null,
      "endDate":"2017-05-17T21:59:00Z",
      "eventStartDateTime":null,
      "extendedData":null,
      "id":86,
      "image":"asi86_high_da-2.png",
      "imageDescription":"Nu er der hele 3 Homestyle burgere på menuen!\r\nVælg mellem Legacy, Chicken Bacon og Tasty. Se mere her.",
      "isActive":true,
      "isAvailableAllStores":true,
      "merchantId":564,
      "placementCode":"CD",
      "startDate":"2017-04-05T22:00:00Z",
      "title":"Nu er der hele 3 Homestyle burgere på menuen!",
      "venues":null,
      "weight":80
   },
   {
      "channelCode":"MAPP",
      "clickThroughUrl":"gmalite://gmalite-smartweb?weburl=https://gmaliteapp.mcd.ddbcph.dk/campaign/mcflurry_mm/",
      "closestVenue":null,
      "contentTagReferenceCodes":[

      ],
      "contentUrl":"",
      "dailyEndTime":null,
      "dailyStartTime":null,
      "dateCreated":"2017-04-03T12:22:29Z",
      "dateModified":"2017-04-06T04:41:50Z",
      "daysOfWeek":[
         0,
         1,
         2,
         3,
         4,
         5,
         6
      ],
      "description":"Prøv den nye McFlurry M&Ms - den er tæt på himmelsk.",
      "distanceToClosestVenue":null,
      "endDate":"2017-07-06T21:59:00Z",
      "eventStartDateTime":null,
      "extendedData":null,
      "id":89,
      "image":"asi89_high_da-2.png",
      "imageDescription":"Nu er den her!\r\nPrøv den nye McFlurry M&Ms - den er tæt på himmelsk.",
      "isActive":true,
      "isAvailableAllStores":true,
      "merchantId":564,
      "placementCode":"CD",
      "startDate":"2017-04-05T22:00:00Z",
      "title":"Nu er den her!",
      "venues":null,
      "weight":70
   },
   {
      "channelCode":"MAPP",
      "clickThroughUrl":"gmalite://gmalite-smartweb?weburl=https://gmaliteapp.mcd.ddbcph.dk/campaign/super_cheese/",
      "closestVenue":null,
      "contentTagReferenceCodes":[

      ],
      "contentUrl":"",
      "dailyEndTime":null,
      "dailyStartTime":null,
      "dateCreated":"2017-04-03T12:10:20Z",
      "dateModified":"2017-04-06T05:51:14Z",
      "daysOfWeek":[
         0,
         1,
         2,
         3,
         4,
         5,
         6
      ],
      "description":"Prøv den nye Super Cheese. Den kan blive din for kun 20 kr.",
      "distanceToClosestVenue":null,
      "endDate":"2017-05-17T21:59:00Z",
      "eventStartDateTime":null,
      "extendedData":null,
      "id":88,
      "image":"asi88_high_da-2.png",
      "imageDescription":"Nyt Coinoffer.\r\nPrøv den nye Super Cheese. Den kan blive din for kun 20 kr.",
      "isActive":true,
      "isAvailableAllStores":true,
      "merchantId":564,
      "placementCode":"CD",
      "startDate":"2017-04-05T22:00:00Z",
      "title":"Nyt Coinoffer",
      "venues":null,
      "weight":60
   },
   {
      "channelCode":"MAPP",
      "clickThroughUrl":"gmalite://gmalite-smartweb?weburl=https://gmaliteapp.mcd.ddbcph.dk/campaign/happymeal-dc-girls/",
      "closestVenue":null,
      "contentTagReferenceCodes":[

      ],
      "contentUrl":"",
      "dailyEndTime":null,
      "dailyStartTime":null,
      "dateCreated":"2017-05-03T14:23:30Z",
      "dateModified":"2017-05-04T06:09:26Z",
      "daysOfWeek":[
         0,
         1,
         2,
         3,
         4,
         5,
         6
      ],
      "description":"Netop nu har vi besøg af figurerne fra DC Super Hero Girls & Justice League Action figurerne!",
      "distanceToClosestVenue":null,
      "endDate":"2017-06-01T21:59:00Z",
      "eventStartDateTime":null,
      "extendedData":null,
      "id":110,
      "image":"asi110_high_da-2.png",
      "imageDescription":"Netop nu har vi besøg af figurerne fra DC Super Hero Girls & Justice League Action figurerne!\r\n",
      "isActive":true,
      "isAvailableAllStores":true,
      "merchantId":564,
      "placementCode":"CD",
      "startDate":"2017-05-04T08:00:00Z",
      "title":"Lige nu i Happy Meal",
      "venues":null,
      "weight":50
   },
   {
      "channelCode":"MAPP",
      "clickThroughUrl":"gmalite://gmalite-smartweb?weburl=https://nutrition-web-dot-prd-euw-gmal-mcdonalds.appspot.com/dk/da-dk/",
      "closestVenue":null,
      "contentTagReferenceCodes":[

      ],
      "contentUrl":"",
      "dailyEndTime":null,
      "dailyStartTime":null,
      "dateCreated":"2017-03-28T11:38:07Z",
      "dateModified":"2017-04-24T08:11:42Z",
      "daysOfWeek":[
         0,
         1,
         2,
         3,
         4,
         5,
         6
      ],
      "description":"Her finder du alle vores produkter.",
      "distanceToClosestVenue":null,
      "endDate":"2018-04-03T11:00:00Z",
      "eventStartDateTime":null,
      "extendedData":null,
      "id":80,
      "image":"asi80_high_en-2.png",
      "imageDescription":"Næring og allergener\r\nHer finder du alt om vores mad og næringsindholdet i den.",
      "isActive":true,
      "isAvailableAllStores":true,
      "merchantId":564,
      "placementCode":"CD",
      "startDate":"2017-04-03T22:00:00Z",
      "title":"Vores mad",
      "venues":null,
      "weight":40
   },
   {
      "channelCode":"MAPP",
      "clickThroughUrl":"http://dublivertilnoget.dk",
      "closestVenue":null,
      "contentTagReferenceCodes":[

      ],
      "contentUrl":"",
      "dailyEndTime":null,
      "dailyStartTime":null,
      "dateCreated":"2017-04-24T07:17:19Z",
      "dateModified":"2017-04-24T10:30:03Z",
      "daysOfWeek":[
         0,
         1,
         2,
         3,
         4,
         5,
         6
      ],
      "description":"Få et overblik over vores ledige stillinger, og søg job her.",
      "distanceToClosestVenue":null,
      "endDate":"2018-01-31T11:00:00Z",
      "eventStartDateTime":null,
      "extendedData":null,
      "id":94,
      "image":"asi94_high_da-2.png",
      "imageDescription":"",
      "isActive":true,
      "isAvailableAllStores":true,
      "merchantId":564,
      "placementCode":"CD",
      "startDate":"2017-04-23T22:00:00Z",
      "title":"Job hos McDonald's",
      "venues":null,
      "weight":40
   },
   {
      "channelCode":"MAPP",
      "clickThroughUrl":"gmalite://gmalite-smartweb?weburl=https://gmaliteapp.mcd.ddbcph.dk/ronald-mcdonald-hus/",
      "closestVenue":null,
      "contentTagReferenceCodes":[

      ],
      "contentUrl":"",
      "dailyEndTime":null,
      "dailyStartTime":null,
      "dateCreated":"2017-03-27T12:20:24Z",
      "dateModified":"2017-05-04T19:35:01Z",
      "daysOfWeek":[
         0,
         1,
         2,
         3,
         4,
         5,
         6
      ],
      "description":"Ronald McDonald Hus er et hjem uden for hjemmet for familier til alvorligt syge børn, der er indlagt på Rigshospitalet. Læs mere om huset og hvordan du kan støtte her.",
      "distanceToClosestVenue":null,
      "endDate":"2018-04-04T21:59:00Z",
      "eventStartDateTime":null,
      "extendedData":null,
      "id":76,
      "image":"asi76_high_da-3.png",
      "imageDescription":"Støt Ronald McDonald Hus.\r\nRonald McDonald Hus er et hjem uden for hjemmet for familier til alvorligt syge børn, der er indlagt på Rigshospitalet. Læs mere om huset og hvordan du kan støtte her.",
      "isActive":true,
      "isAvailableAllStores":true,
      "merchantId":564,
      "placementCode":"CD",
      "startDate":"2017-04-02T22:00:00Z",
      "title":"Støt Ronald McDonald Hus",
      "venues":null,
      "weight":30
   },
   {
      "channelCode":"MAPP",
      "clickThroughUrl":"gmalite://gmalite-smartweb?weburl=https://gmaliteapp.mcd.ddbcph.dk/mcdonalds-pa-de-sociale-medier/",
      "closestVenue":null,
      "contentTagReferenceCodes":[

      ],
      "contentUrl":"",
      "dailyEndTime":null,
      "dailyStartTime":null,
      "dateCreated":"2017-03-27T12:22:56Z",
      "dateModified":"2017-04-06T04:43:45Z",
      "daysOfWeek":[
         0,
         1,
         2,
         3,
         4,
         5,
         6
      ],
      "description":"Husk at du altid kan hænge med os på de sociale medier. Se mere her.",
      "distanceToClosestVenue":null,
      "endDate":"2018-04-03T21:59:00Z",
      "eventStartDateTime":null,
      "extendedData":null,
      "id":77,
      "image":"asi77_high_da-3.png",
      "imageDescription":"McDonald's på sociale medier\r\n\r\nHusk at du altid kan hænge med os på de sociale medier. Se mere her.",
      "isActive":true,
      "isAvailableAllStores":true,
      "merchantId":564,
      "placementCode":"CD",
      "startDate":"2017-04-02T22:00:00Z",
      "title":"McDonald's på sociale medier",
      "venues":null,
      "weight":20
   }
]
